<a href="https://colab.research.google.com/github/mssuhas/IIIT-training/blob/main/IIIT_training_D2_example1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importing data handling libraries

import pandas as pd
import numpy as np

In [ ]:
path=("/content/iris.csv")

In [ ]:
iris_dataset_frame = pd.read_csv(path, header=None)
print("Iris dataset dataframe looks like \n", iris_dataset_frame)

Iris dataset dataframe looks like 
        0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]


In [ ]:
#Transforming the dataframe into numpy matrices

iris_dataset = iris_dataset_frame.to_numpy()
print("Iris Dataset: \n", iris_dataset, "\n")
print("np.shape(iris_dataset): ", iris_dataset.shape, "\n")


Iris Dataset: 
 [[5.1 3.5 1.4 0.2 'Iris-setosa']
 [4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 [4.6 3.1 1.5 0.2 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']
 [5.4 3.9 1.7 0.4 'Iris-setosa']
 [4.6 3.4 1.4 0.3 'Iris-setosa']
 [5.0 3.4 1.5 0.2 'Iris-setosa']
 [4.4 2.9 1.4 0.2 'Iris-setosa']
 [4.9 3.1 1.5 0.1 'Iris-setosa']
 [5.4 3.7 1.5 0.2 'Iris-setosa']
 [4.8 3.4 1.6 0.2 'Iris-setosa']
 [4.8 3.0 1.4 0.1 'Iris-setosa']
 [4.3 3.0 1.1 0.1 'Iris-setosa']
 [5.8 4.0 1.2 0.2 'Iris-setosa']
 [5.7 4.4 1.5 0.4 'Iris-setosa']
 [5.4 3.9 1.3 0.4 'Iris-setosa']
 [5.1 3.5 1.4 0.3 'Iris-setosa']
 [5.7 3.8 1.7 0.3 'Iris-setosa']
 [5.1 3.8 1.5 0.3 'Iris-setosa']
 [5.4 3.4 1.7 0.2 'Iris-setosa']
 [5.1 3.7 1.5 0.4 'Iris-setosa']
 [4.6 3.6 1.0 0.2 'Iris-setosa']
 [5.1 3.3 1.7 0.5 'Iris-setosa']
 [4.8 3.4 1.9 0.2 'Iris-setosa']
 [5.0 3.0 1.6 0.2 'Iris-setosa']
 [5.0 3.4 1.6 0.4 'Iris-setosa']
 [5.2 3.5 1.5 0.2 'Iris-setosa']
 [5.2 3.4 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.6 0.2 'Iris-set

In [ ]:
#Separating the features from labels in the dataset

iris_dataset_features = iris_dataset[:,0:4]
iris_dataset_labels = iris_dataset[:,4]
print("np.shape(iris_dataset_features): ", np.shape(iris_dataset_features), "\n")
print("np.shape(iris_dataset_labels): ", np.shape(iris_dataset_labels))


np.shape(iris_dataset_features):  (150, 4) 

np.shape(iris_dataset_labels):  (150,)


In [ ]:
#Perform train-test split on the dataset

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(iris_dataset_features, iris_dataset_labels, test_size=0.20, random_state=42)


In [ ]:
#Getting the training data characteristics

print("x_train: \n", x_train, "\n")
print("np.shape(x_train): ", np.shape(x_train), "\n")
print("y_train: \n", y_train, "\n")
print("np.shape(y_train)", np.shape(y_train), "\n")


x_train: 
 [[4.6 3.6 1.0 0.2]
 [5.7 4.4 1.5 0.4]
 [6.7 3.1 4.4 1.4]
 [4.8 3.4 1.6 0.2]
 [4.4 3.2 1.3 0.2]
 [6.3 2.5 5.0 1.9]
 [6.4 3.2 4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [5.0 3.6 1.4 0.2]
 [5.2 4.1 1.5 0.1]
 [5.8 2.7 5.1 1.9]
 [6.0 3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [5.4 3.9 1.3 0.4]
 [5.4 3.7 1.5 0.2]
 [5.5 2.4 3.7 1.0]
 [6.3 2.8 5.1 1.5]
 [6.4 3.1 5.5 1.8]
 [6.6 3.0 4.4 1.4]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9 4.2 1.3]
 [7.6 3.0 6.6 2.1]
 [5.6 3.0 4.5 1.5]
 [5.1 3.5 1.4 0.2]
 [7.7 2.8 6.7 2.0]
 [5.8 2.7 4.1 1.0]
 [5.2 3.4 1.4 0.2]
 [5.0 3.5 1.3 0.3]
 [5.1 3.8 1.9 0.4]
 [5.0 2.0 3.5 1.0]
 [6.3 2.7 4.9 1.8]
 [4.8 3.4 1.9 0.2]
 [5.0 3.0 1.6 0.2]
 [5.1 3.3 1.7 0.5]
 [5.6 2.7 4.2 1.3]
 [5.1 3.4 1.5 0.2]
 [5.7 3.0 4.2 1.2]
 [7.7 3.8 6.7 2.2]
 [4.6 3.2 1.4 0.2]
 [6.2 2.9 4.3 1.3]
 [5.7 2.5 5.0 2.0]
 [5.5 4.2 1.4 0.2]
 [6.0 3.0 4.8 1.8]
 [5.8 2.7 5.1 1.9]
 [6.0 2.2 4.0 1.0]
 [5.4 3.0 4.5 1.5]
 [6.2 3.4 5.4 2.3]
 [5.5 2.3 4.0 1.3]
 [5.4 3.9 1.7 0.4]
 [5.0 2.3 3.3 1.0]
 [6.4 2.7 5.3 1.9]
 [5.0 3.3 1.4 0.2]
 

In [ ]:
#Getting the testing data characteristics

print("x_test: \n", x_test, "\n")
print("np.shape(x_test)", np.shape(x_test), "\n")
print("y_test: \n", y_test, "\n")
print("np.shape(y_test)", np.shape(y_test), "\n")


x_test: 
 [[6.1 2.8 4.7 1.2]
 [5.7 3.8 1.7 0.3]
 [7.7 2.6 6.9 2.3]
 [6.0 2.9 4.5 1.5]
 [6.8 2.8 4.8 1.4]
 [5.4 3.4 1.5 0.4]
 [5.6 2.9 3.6 1.3]
 [6.9 3.1 5.1 2.3]
 [6.2 2.2 4.5 1.5]
 [5.8 2.7 3.9 1.2]
 [6.5 3.2 5.1 2.0]
 [4.8 3.0 1.4 0.1]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [5.1 3.8 1.5 0.3]
 [6.3 3.3 4.7 1.6]
 [6.5 3.0 5.8 2.2]
 [5.6 2.5 3.9 1.1]
 [5.7 2.8 4.5 1.3]
 [6.4 2.8 5.6 2.2]
 [4.7 3.2 1.6 0.2]
 [6.1 3.0 4.9 1.8]
 [5.0 3.4 1.6 0.4]
 [6.4 2.8 5.6 2.1]
 [7.9 3.8 6.4 2.0]
 [6.7 3.0 5.2 2.3]
 [6.7 2.5 5.8 1.8]
 [6.8 3.2 5.9 2.3]
 [4.8 3.0 1.4 0.3]
 [4.8 3.1 1.6 0.2]] 

np.shape(x_test) (30, 4) 

y_test: 
 ['Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa

In [ ]:
# Defining our Support Vector Machine (SVM) classifier

from sklearn.svm import SVC
svm_classifier = SVC(C=5.0, kernel = 'linear', gamma = 'scale')
print("SVM Classifier: \n", svm_classifier,"\n")


SVM Classifier: 
 SVC(C=5.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False) 



In [ ]:
#Training our classifier

svm_classifier.fit(x_train, y_train)

#Getting the classifier arguments

print("Printing the support vectors \n\n", svm_classifier.support_vectors_, "\n")
print("Number of support vectors: ", np.shape(svm_classifier.support_vectors_)[0], "\n")

print("Number of support vectors for each class: ", svm_classifier.n_support_)
print("Intercept values: ", svm_classifier.intercept_)


Printing the support vectors 

 [[4.8 3.4 1.9 0.2]
 [5.1 3.3 1.7 0.5]
 [4.5 2.3 1.3 0.3]
 [5.6 3.  4.5 1.5]
 [5.4 3.  4.5 1.5]
 [6.7 3.  5.  1.7]
 [5.9 3.2 4.8 1.8]
 [5.1 2.5 3.  1.1]
 [6.  2.7 5.1 1.6]
 [6.3 2.5 4.9 1.5]
 [6.3 2.3 4.4 1.3]
 [6.3 2.8 5.1 1.5]
 [6.3 2.7 4.9 1.8]
 [6.  3.  4.8 1.8]
 [6.2 2.8 4.8 1.8]
 [7.2 3.  5.8 1.6]
 [5.9 3.  5.1 1.8]
 [4.9 2.5 4.5 1.7]] 

Number of support vectors:  18 

Number of support vectors for each class:  [3 8 7]
Intercept values:  [1.45338269 1.50537328 5.9640843 ]


In [ ]:
#Making predictions using the SVM model

svm_predictions = svm_classifier.predict(x_test)
print("Predictions: \n", svm_predictions)


Predictions: 
 ['Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa']


In [ ]:
#Comparing the predictions with the ground truth

print("Predictions \t Ground Truth: \n\n", np.column_stack((svm_predictions, y_test)))


Predictions 	 Ground Truth: 

 [['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-virginica' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-virginica' 'Iris-virginica']
 

In [ ]:
#Quantifying the performance of the model on the test data

accuracy = svm_classifier.score(x_test, y_test)
print("Classifier Accuracy:: ", accuracy, "\n")


Classifier Accuracy::  0.9666666666666667 



In [ ]:
#Getting the confusion matrix for the predictions

from sklearn.metrics import confusion_matrix 
cm = confusion_matrix(y_test, svm_predictions)
print("Confusion Matrix: \n\n", cm, "\n")

Confusion Matrix: 

 [[10  0  0]
 [ 0  8  1]
 [ 0  0 11]] 

